version: '3.5'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: nestnook
    volumes:
      - mongodata:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nestnook
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'

volumes:
  postgres:
  mongodata:
